In [1]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import matplotlib.cm as cm
%matplotlib inline
from matplotlib import patches
from google.colab import drive
drive.mount('/content/gdrive')

Using TensorFlow backend.


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [2]:
# read the csv file using read_csv function of pandas
train = pd.read_csv('gdrive/My Drive/Colab Notebooks/training_set.csv')
train.size


120000

In [0]:
dataset_csv = pd.read_csv('gdrive/My Drive/Colab Notebooks/training_set.csv',index_col=None)
dataset = dataset_csv[['image_name','x1','x2','y1','y2']]

In [0]:
x_train_array = []
y_train_array = []
for i in range(0,24000):
  img = mpimg.imread('gdrive/My Drive/Colab Notebooks/resize160120/'+str(x_train[i][0]))
  print(i)
  gray = rgb2gray(img)    
  x_train_array.append(gray)
  y_train_array.append(y_train[i])
print(np.array(y_train_array))
x_train_array = np.array(x_train_array)
y_train_array = np.array(y_train_array)

KeyboardInterrupt: ignored

In [4]:
x_train = dataset[['image_name']]
x_train = np.asarray(x_train)
y_train = dataset[['x1','x2','y1','y2']]
y_train = np.asarray(y_train]

SyntaxError: ignored

In [5]:
print(x_train[86:89])

NameError: ignored

In [0]:
https://www.kaggle.com/nvhbk16k53/simple-rnn-with-keras

In [6]:

x_train_array = np.load('gdrive/My Drive/Colab Notebooks/Numpy/x_train_array.npy')
y_train_array = np.load('gdrive/My Drive/Colab Notebooks/Numpy/y_train_array.npy')
#Model training
print(len(x_train_array))
x_train_array = x_train_array.reshape(x_train_array.shape[0],48,64,1)


24000


In [0]:
x_retrain_array = np.load('gdrive/My Drive/Colab Notebooks/Numpy/x_train_array_retrain.npy')
y_retrain_array = np.load('gdrive/My Drive/Colab Notebooks/Numpy/y_train_array_retrain.npy')
#Model training
print(len(x_retrain_array))
x_retrain_array = x_retrain_array.reshape(x_retrain_array.shape[0],48,64,1)

In [0]:
#Model training

#Model training
model = Sequential()

model.add(Conv2D(128, kernel_size=(2,2), activation = 'relu', input_shape = (32,32,1)))
model.add(Conv2D(256, (2,2), activation = 'relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(512, (2,2), activation = 'relu'))
#model.add(MaxPooling2D(pool_size=(2,2)))
#model.add(Conv2D(256, (2,2), activation = 'relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))


#model.add(Dense(6144,activation = 'relu'))
#model.add(Dropout(0.2))
model.add(Dense(2048,activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(1024,activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(256,activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(128,activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(64,activation = 'relu'))
model.add(Dropout(0.2))

model.add(Conv2D(512, (2,2), activation = 'softplus'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dense(1024,activation = 'relu'))
model.add(Dropout(0.2))
model.add(Conv2D(256, (2,2), activation = 'softplus'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))

model.add(Dense(1024,activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(512,activation = 'softplus'))
model.add(Dropout(0.2))
model.add(Dense(256,activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(128,activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(64,activation = 'relu'))
model.add(Dropout(0.2))

model.add(Flatten())
model.add(Dense(4,activation = 'relu'))


model.compile(loss=keras.losses.mean_squared_error,optimizer=keras.optimizers.Adamax(),metrics=['accuracy'])
print(model.summary())
model.fit(x_train_array, y_train_array,batch_size=16,epochs=10,verbose=1)


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_27 (Conv2D)           (None, 31, 31, 128)       640       
_________________________________________________________________
conv2d_28 (Conv2D)           (None, 30, 30, 256)       131328    
_________________________________________________________________
max_pooling2d_21 (MaxPooling (None, 15, 15, 256)       0         
_________________________________________________________________
conv2d_29 (Conv2D)           (None, 14, 14, 512)       524800    
_________________________________________________________________
max_pooling2d_22 (MaxPooling (None, 7, 7, 512)         0         
_________________________________________________________________
dropout_60 (Dropout)         (None, 7, 7, 512)         0         
_________________________________________________________________
dense_55 (Dense)             (None, 7, 7, 2048)        1050624   
__________

KeyboardInterrupt: ignored

In [0]:
#Model training
model = Sequential()

model.add(Conv2D(128, kernel_size=(3,3), activation = 'relu', input_shape = (48,64,1)))
model.add(Conv2D(256, (3,3), activation = 'relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(512, (3,3), activation = 'relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(256, (3,3), activation = 'relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(2048,activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(1024,activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(512,activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(256,activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(4,activation = 'relu'))


model.compile(loss=keras.losses.mean_squared_error,optimizer=keras.optimizers.Adamax(),metrics=['accuracy'])
print(model.summary())
model.fit(x_train_array[0:24000], y_train_array[0:24000],batch_size=16,epochs=50,verbose=1)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 46, 62, 128)       1280      
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 44, 60, 256)       295168    
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 22, 30, 256)       0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 20, 28, 512)       1180160   
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 10, 14, 512)       0         
_________________________________________________________________
conv2d_4 (Conv2D)    

In [0]:
model.fit(x_retrain_array[0:28000], y_retrain_array[0:28000],batch_size=16,epochs=3,verbose=1)

Epoch 1/3
24000/24000 [==============================] - 105s 4ms/step - loss: 748.2449 - acc: 0.9721
Epoch 2/3
24000/24000 [==============================] - 106s 4ms/step - loss: 784.2885 - acc: 0.9727
Epoch 3/3
24000/24000 [==============================] - 106s 4ms/step - loss: 696.5688 - acc: 0.9710


In [0]:
predicted_array = model.predict(x_train_array)
print(predicted_array)


[[ 79.51148  455.15903   61.34622  421.49344 ]
 [ 68.01598  558.60364  144.16928  342.9456  ]
 [ 21.418203 561.9504   113.525314 363.55984 ]
 ...
 [115.62505  572.0211    44.31834  439.77798 ]
 [ 45.272053 558.9855   106.04815  410.2662  ]
 [ 69.737816 550.2841   150.11803  333.56555 ]]


In [0]:
print(np.round(predicted_array))

[[ 82. 440.  91. 409.]
 [ 61. 568. 137. 354.]
 [ 25. 588. 115. 381.]
 ...
 [109. 572.  35. 438.]
 [ 48. 594.  90. 421.]
 [ 71. 540. 153. 333.]]


In [0]:
iou = []
for i in range(0,24000):
    #print(predicted_array[i], y_train_array[i])
    iou.append(abs(bb_intersection_over_union(np.round(predicted_array)[i], y_train_array[i])))
    #print(bb_intersection_over_union(predicted_array[i], y_train_array[i])) 
iou = np.array(iou)
print(sum(iou)/len(iou))

0.8940208691041107


In [0]:

def bb_intersection_over_union(boxA, boxB):
	# determine the (x, y)-coordinates of the intersection rectangle
	xA = max(boxA[0], boxB[0])
	xB = min(boxA[1], boxB[1])
	yA = max(boxA[2], boxB[2])
	yB = min(boxA[3], boxB[3])
    
	# compute the area of intersection rectangle
	interArea = max(0,xB - xA + 1) * max(0, yB - yA + 1)
    
	# compute the area of both the prediction and ground-truth
	# rectangles
	boxAArea = (boxA[1] - boxA[0] + 1) * (boxA[3] - boxA[2] + 1)
	boxBArea = (boxB[1] - boxB[0] + 1) * (boxB[3] - boxB[2] + 1)
	#print(boxAArea + boxBArea,interArea)
    
	# compute the intersection over union by taking the intersection
	# area and dividing it by the sum of prediction + ground-truth
	# areas - the interesection area
	iou = interArea / float(boxAArea + boxBArea - interArea)
 
	# return the intersection over union value
	return iou

In [0]:
import csv
with open('gdrive/My Drive/Colab Notebooks/testing.csv','w') as myoutputfile:
    myoutputfile.write('image_name,x1,x2,y1,y2\n')
    i = 0
    for row in predicted_array:
        myoutputfile.write(str(x_test[i,0])+','+str(abs(int(row[0])))+','+str(abs(int(row[1])))+','+str(abs(int(row[2])))+','+str(abs(int(row[3])))+'\n')
        i=i+1
    myoutputfile.close()
    

In [0]:
'''Test dataset''' 
test_dataset = pd.read_csv('gdrive/My Drive/Colab Notebooks/test_set.csv',index_col=None)
x_test = test_dataset[['image_name']]
x_test = np.asarray(x_test)
y_test = test_dataset[['x1','x2','y1','y2']]
y_test = np.asarray(y_test)

In [0]:
x_test_array = np.load('gdrive/My Drive/Colab Notebooks/Numpy/x_train_array_test.npy')
#np.save('D:\\Project\\flipkart challenge\\images\\resize\\'+str('x_test_array'),x_test_array)
x_test_array = x_test_array.reshape(x_test_array.shape[0],48,64,1)

In [0]:
predicted_array = model.predict(x_test_array)
print(predicted_array)

[[ 79.24729   560.09717    73.18056   431.609    ]
 [225.85008   427.88873   104.92806   427.72162  ]
 [204.99481   430.52124    91.24704   383.31384  ]
 ...
 [107.10057   526.9608    125.17465   382.49304  ]
 [ 12.1064825 612.55896    10.79326   480.1838   ]
 [  0.        624.95905   110.44013   354.64066  ]]
